### ISSUE TITLE
SSIM implementation in common.py is wrong: Colors are gamma-corrected two times.

### ISSUE THREAD

**Issue by mcourteaux** [NVlabs/instant-ngp#1009]
First occurrence is here:
https://github.com/NVlabs/instant-ngp/blob/51e4107edf48338e9ab0316d56a222e0adf87143/scripts/run.py#L287-L290

And then the SSIM call computes luminance incorrectly:
https://github.com/NVlabs/instant-ngp/blob/51e4107edf48338e9ab0316d56a222e0adf87143/scripts/common.py#L186-L207

First the power of 0.4545454545 is equivalent to gamma correction, and the `linear_to_sRGB` function from earlier does something similar. Note that the function `luminance` computes what we call "luma" (which is a stupid concept historically introduced for engineering reasons upon invention of color TV), given linear colors.

I don't know what the input of the official SSIM function should be: luminance or gamma corrected luminance. But right now, you compute it using double gamma corrected values.

**Comment by Tom94** [comment]
Good catch, thanks! Fixed in https://github.com/NVlabs/instant-ngp/commit/102aad63ba0af32b0980d3770022dfbccabbdf85

All the error metrics were originally used in codebases that computed linear-space images exclusively, in which case the tonemapping operation was okay, but it's probably good practice to disentangle the two completely.

I agree w.r.t. luminance in linear space -- but I'm holding off refactoring the SSIM code to produce RGB error values for now due to lack of priority.
