### ISSUE TITLE
Switching to single view and back stops rendering in testbed

### ISSUE THREAD

**Issue by jhurlbut** [NVlabs/instant-ngp#106]
Is there any documentation of the multiple view mode? When activating single view and then deactivating the render view is mostly back with speckles of red and green.

**Comment by Tom94** [comment]
Hi there, when switching back to single view mode, the visualized dimension hasn't been reset, so you're likely looking at the last input dimension to the neural network, rather than the actual rendering.

Admittedly, this isn't very intuitive behavior -- I've fixed it up on `master` (https://github.com/NVlabs/instant-ngp/commit/f55f8241c681dfa3f6c837736684327e737f9678)
