### ISSUE TITLE
'C:\ngp\instant-ngp\build\testbed.exe' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by paracanthurus25** [NVlabs/instant-ngp#1143]
I'm trying to run the "C:\ngp\instant-ngp\build\testbed.exe --scene data/<name>" command and I get this error:

'C:\ngp\instant-ngp\build\testbed.exe' is not recognized as an internal or external command,
operable program or batch file.

**Comment by paracanthurus25** [comment]
Ah, so I guess the application is called instant-ngp.exe now.

**Comment by manotti22** [comment]
hello- can someone help me
if i run this command :
(ngp) C:\ngp\instant-ngp>C:\ngp\instant-ngp\build\testbed.exe --scene data/drums
i got this error
**'C:\ngp\instant-ngp\build\testbed.exe' is not recognized as an internal or external command,
operable program or batch file.**
if i add instant-ngp.exe
i got this error
(ngp) C:\ngp\instant-ngp>C:\ngp\instant-ngp.exe\build\testbed.exe --scene data/drums
**The system cannot find the path specified.**

thank you

**Comment by paracanthurus25** [comment]
Try running this command:   C:\ngp\instant-ngp\build\instant-ngp.exe --scene data/drums

**Comment by manotti22** [comment]
i run it . i got this error:
instant-ngp.exe error system 
**Unable to execute code because nvcuda.dll could not be found-reinstalling the program may correct this problem**

i installed nvidia cuda tollkit 11.6 and microsoft visual code 19. i have windows 10 . 
how i can solve this problem ? 
thank you for your answer

**Comment by manotti22** [comment]
i install nvcuda.dll files in my system .

now i got this error :
(ngp) C:\ngp\instant-ngp> C:\ngp\instant-ngp\build\instant-ngp.exe --scene data/drums

**14:24:41 ERROR    Uncaught exception: C:\ngp\instant-ngp\dependencies\tiny-cuda-nn\include\tiny-cuda-nn/multi_stream.h:44 cudaStreamCreate(&m_stream) failed with error CUDA driver version is insufficient for CUDA runtime version**

how i can fix this ?
thank you in advance

**Comment by Tom94** [comment]
Hi, can you try installing the latest driver for your graphics card from [here](https://www.nvidia.com/download/index.aspx)? `nvcuda.dll` should automatically be included -- although I am surprised that your previous CUDA installation did not come with a graphics driver. Usually it does.

**Comment by manotti22** [comment]
hi, i try to install the latest nvidia Graphic driver, by checking system compatibility , Nvidia Installer cannot continue because the drivers grahic is not compatible with my windows versions.
![Screenshot (39)](https://user-images.githubusercontent.com/97608984/216995009-c60f92cf-bc70-457b-875b-5b138eee8d1e.png)

i have windows 10 and i try to install nvidia driver Graphic  windows 10 , but doesn work.
are there any other version that are suitable for windows 10 ?
