### ISSUE TITLE
What is this algorithm?

### ISSUE THREAD

**Issue by jc211** [NVlabs/instant-ngp#123]
Below looks like some kind of pseudo random number generator. Any reference to the algorithm used here?

https://github.com/NVlabs/instant-ngp/blob/892933b5cfa673c98216cd0fe9b3c2b0f86d9128/src/testbed_nerf.cu#L449

**Comment by Tom94** [comment]
It's a [linear congruential generator](https://en.wikipedia.org/wiki/Linear_congruential_generator), which is a form of pseudo-random number generator. Its statistical properties are somewhat bad, but it is very efficient.

Here, we don't actually care much about its statistical properties. Rather, we care about its property of producing a _permutation_: this use case distributes the density grid update samples more-or-less uniformly over space (due to the pseudo-random nature), but ensures good coverage by never visiting a grid cell twice without having visited all other cells (due to the permutation property).

Feel free to re-open the issue if something is still unclear!
