### ISSUE TITLE
RuntimeError: /instant-ngp/src/testbed_nerf.cu:2216 cudaMemsetAsync(density_grid_tmp, 0, sizeof(float)*n_elements, stream) failed with error invalid argument

### ISSUE THREAD

**Issue by bruinxiong** [NVlabs/instant-ngp#129]
After update codes and rebuild again, I ran nerf expriment and met this error as follows:

Traceback (most recent call last):
  File "scripts/run.py", line 186, in <module>
    while testbed.frame():

RuntimeError: /instant-ngp/src/testbed_nerf.cu:2216 cudaMemsetAsync(density_grid_tmp, 0, sizeof(float)*n_elements, stream) failed with error invalid argument

**Comment by Tom94** [comment]
Hi there, could you pull latest master, update submodules, and try again?

(__tiny-cuda-nn__ should be on https://github.com/NVlabs/tiny-cuda-nn/commit/d7b408bfc501a45d27a04f2b72aceb0b16286c05)

If this doesn't fix the issue, could you provide additional information about your system?
- OS
- Which GPUs are installed
- What's the command that leads to the crash, and
- Does the crash also happen when running the `testbed` binary instead of `run.py`?

Thanks!
