### ISSUE TITLE
Run Detectron2 on image folder before Colmap

### ISSUE THREAD

**Issue by gradeeterna** [NVlabs/instant-ngp#1308]
Hey,

I've noticed that running Detectron2 from colmap2nerf requires the colmap_sparse and colmap_text folders from the alignment in order to generate the masks.

I mainly use Metashape and Reality Capture for alignment, so it would be great to be able to run Detectron2 on the whole image folder without needing to run Colmap, e.g. python scripts/colmap2nerf.py --images data\images --mask_categories person

Thanks!

**Comment by Avuerro** [comment]
Hi,

You could try adding ```--run_colmap False``` to your command. I would expect it to stop Colmap from running.

**Comment by cpkcpkcpk** [comment]
Hey, thanks for the reply. `--run_colmap False` isn't an option, but leaving out `--run_colmap` does stop it from running. I think the issue is that it's creating masks for the images included in colmap_text\cameras.txt, rather than the image folder written in the command.

`(ngp) E:\InstantNGPGit\instant-ngp>python scripts/colmap2nerf.py --images data\test --mask_categories person
outputting to transforms.json...
Traceback (most recent call last):
  File "E:\InstantNGPGit\instant-ngp\scripts\colmap2nerf.py", line 205, in <module>
    with open(os.path.join(TEXT_FOLDER,"cameras.txt"), "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'colmap_text\\cameras.txt'`

**Comment by gradeeterna** [comment]
Hey, thanks for the reply. `--run_colmap False` isn't an option, but leaving out `--run_colmap` does stop it from running. I think the issue is that it's creating masks for the images included in colmap_text\cameras.txt, rather than the image folder written in the command.

`(ngp) E:\InstantNGPGit\instant-ngp>python scripts/colmap2nerf.py --images data\test --mask_categories person outputting to transforms.json... Traceback (most recent call last): File "E:\InstantNGPGit\instant-ngp\scripts\colmap2nerf.py", line 205, in <module> with open(os.path.join(TEXT_FOLDER,"cameras.txt"), "r") as f: FileNotFoundError: [Errno 2] No such file or directory: 'colmap_text\\cameras.txt'`

**Comment by Tom94** [comment]
Hi, I added a standalone script `./scripts/mask_images.py --images <image folder> --mask_categories <categories>` that'll do the job independently from COLMAP.

**Comment by gradeeterna** [comment]
Perfect, thanks a lot Thomas!
