### ISSUE TITLE
the different shooting distances affect the 3D reconstruction results

### ISSUE THREAD

**Issue by fengbingchun** [NVlabs/instant-ngp#1322]
I take a set of 360-degree image sequences, and if the phone is always at a relatively same distance from the object being photographed when shooting, the result of the 3D reconstruction is good.
If the distance between the phone and the object being photographed changes greatly during the shooting process, the 3D reconstruction effect is very poor.
Why is there such an impact? What are the considerations when shooting a test image set? thank you.

**Comment by pierre-wilmot** [comment]
See the MipNerf paper. They describe this very problem.
It should get better as you let the app run without moving the view and start to accumulate more sample per pixels.
But the gist of the problem is that you sample a point in space, whereas a pixel really represent an area.
Viewed from far away, each pixel shoud output an average of the colors in the area it covers, and there is nothing in iNGP to account for that yet (except for the supersampling, which I think now has been replaced by DLSS).

**Comment by fengbingchun** [comment]
@pierre-wilmot  I understood. Thank you very much for your reply.
