### ISSUE TITLE
Mesh is a bit blurry and rough

### ISSUE THREAD

**Issue by joseph16388** [NVlabs/instant-ngp#1333]
Is there any way to make 3D mesh more detailed after applying instant-ngp mesh saveit！ and importing it into meshlab？
![fox](https://user-images.githubusercontent.com/117060507/232999487-d1930658-0c18-49df-bdc3-27a8fcb56aeb.png)

**Comment by JoeLoginIsAlreadyTaken** [comment]
The Fox example is not the best idea for trying out mesh export, auf the images are small, and noisy.
Fur is also not the ideal texture to be meshed.
Anyway, first you should adjust the crop-box  to the part you really want to mesh, just the fox for example.
Than you have to increase the mesh resolution. 
![fox1](https://user-images.githubusercontent.com/35426186/233789549-9aff5e1c-a613-42c2-8691-24321a003601.jpg)

Mesh it, and save the mesh.

Open the file in Meshlab and clean it up.
This is the hard part because meshlab gets quite slow with huge meshes.

![fox2](https://user-images.githubusercontent.com/35426186/233789973-bdac9789-0cce-4987-a659-b823074978a7.jpg)


I first use "Remove Isolated pieces (wrt Diameter)" to remove some of the noise.

![fox3](https://user-images.githubusercontent.com/35426186/233789992-6eae22f7-457b-4384-b3d2-5ebc1e43c4a1.jpg)

If possible cut away whats not needed.

![fox4](https://user-images.githubusercontent.com/35426186/233790357-5362e6fb-9e94-44d6-a9d1-9f061c97ddf2.jpg)

You should at least now save a copy. :-)

After that a usually use "Surface Reconstruction: Screened Poison". Increase the number of samples and maybe the interpolation. 

![fox5](https://user-images.githubusercontent.com/35426186/233790735-41d2c6d6-d539-4f88-a0e9-5aaaf613e8c4.jpg)

This already looks quite good.

![fox6](https://user-images.githubusercontent.com/35426186/233790887-3386d462-e730-4a30-8960-bcd4dca946c2.jpg)

Next time to save the new mesh, as the next operation sometimes crashes.

The i use the paint marker (red pen) to select all the relevant surfaces but not the inside bubbles.

![fox7](https://user-images.githubusercontent.com/35426186/233790951-32e62335-5964-4b52-8bcd-d09b5c07b329.jpg)

Invert the selection and remove most of the inside bubbles.

![fox8](https://user-images.githubusercontent.com/35426186/233791319-820b4c88-7652-495d-aa29-b50afa8d3a51.jpg)

After that the Mesh is nearly empty und down to a decent amount of verticals.

That's the point where i usually move over to blender, do some more cleanup and than do a "Remesh".

![fox9](https://user-images.githubusercontent.com/35426186/233791601-a85463d6-c6e7-4404-8798-0e654a902477.jpg)

But as already mentioned, the fox sample is not ideal for meshing.

**Comment by JoeLoginIsAlreadyTaken** [comment]
If you get a "out of memory" error when meshing a higher resolution, try to save the scene as a snapshot (*.ingp) after the training is good. Close instant ngp and open it again, load the ingp-file.
Now there is no training and you have much more free memory for meshing.

**Comment by joseph16388** [comment]
Thank U!
