### ISSUE TITLE
Error on Building CUDA object CMakeFiles/ngp.dir/src/testbed.cu.o

### ISSUE THREAD

**Issue by cyrstem** [NVlabs/instant-ngp#1372]
i recently update my system and this repo  and when trying to rebuild  i get this error :```
 Building CUDA object CMakeFiles/ngp.dir/src/testbed.cu.o
/home/jacos/instant-ngp/src/testbed.cu: In member function ‘void ngp::Testbed::set_mode(ngp::ETestbedMode)’:
/home/jacos/instant-ngp/src/testbed.cu:175:23: error: no match for ‘operator=’ (operand types are ‘ngp::Testbed::Volume’ and ‘<brace-enclosed initializer list>’)
  175 |         m_volume = {};
      |                       ^
/home/jacos/instant-ngp/include/neural-graphics-primitives/testbed.h:852:15: note: candidate: ‘ngp::Testbed::Volume& ngp::Testbed::Volume::operator=(ngp::Testbed::Volume&&)’
  852 |         struct Volume {
      |               ^~~~~~
/home/jacos/instant-ngp/include/neural-graphics-primitives/testbed.h:852:15: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘ngp::Testbed::Volume&&’
make[2]: *** [CMakeFiles/ngp.dir/build.make:299: CMakeFiles/ngp.dir/src/testbed.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:308: CMakeFiles/ngp.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by mozuysal** [comment]
I had the same problem while compiling. The volume variable of type struct Testbed::Volume is assigned to an empty initializer list in function  ‘void ngp::Testbed::set_mode(ngp::ETestbedMode)' with
      volume = {}
which seems to be the origin of the problem. Similar structures like Testbed::Image does not seem to create any issues.

Initialization of the two arrays of length 2 inside Testbed::Volume around L867 in testbed.h is likely the source of errors:
// tracing state
		tcnn::GPUMemory<vec3> pos[2] = {};
		tcnn::GPUMemory<VolPayload> payload[2] = {};
since these are arrays and the single initilizer list is possibly what trips the compiler. Changing these lines to
// tracing state
		tcnn::GPUMemory<vec3> pos[2] = {{}, {}};
		tcnn::GPUMemory<VolPayload> payload[2] = {{},{}};
solved the compilation errors and the code seems to work fine after the changes. However, I am not 100% sure this is the best solution. 

Hope this helps.

For reference my GCC and NVCC version information is given below:
$ g++ --version
g++ (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0

**Comment by cyrstem** [comment]
@mozuysal thanks it help!! but now i get this:
```
/home/jacos/instant-ngp/src/python_api.cu:616:140:   required from here
/home/jacos/instant-ngp/dependencies/pybind11_glm/pybind11_glm.hpp:43:33: warning: ‘pybind11::array_t<T, ExtraFlags>::array_t(pybind11::handle, bool) [with T = int; int ExtraFlags = 16]’ is deprecated: Use array_t<T>::ensure() instead [-Wdeprecated-declarations]
   43 |                 array_t<Scalar> buf(src, true);
      |                                 ^~~
/home/jacos/instant-ngp/dependencies/pybind11/include/pybind11/numpy.h:1037:1: note: declared here
 1037 |     array_t(handle h, bool is_borrowed) : array(raw_array_t(h.ptr()), stolen_t{}) {
      | ^   ~~~
/home/jacos/instant-ngp/dependencies/pybind11_glm/pybind11_glm.hpp:44:29: warning: ‘bool pybind11::array::check() const’ is deprecated: Use py::isinstance<py::python_type>(obj) instead [-Wdeprecated-declarations]
   44 |                 if (!buf.check())
      |                    ~~~~~~~~~^~
/home/jacos/instant-ngp/dependencies/pybind11/include/pybind11/numpy.h:682:385: note: declared here
  682 |     PYBIND11_OBJECT_CVT(array, buffer, detail::npy_api::get().PyArray_Check_, raw_array)
      |                                                                                                                                                                                                                                                                                                                                                                                                 ^
make[2]: *** [CMakeFiles/pyngp.dir/build.make:77: CMakeFiles/pyngp.dir/src/python_api.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:368: CMakeFiles/pyngp.dir/all] Error 2
```
maybe another tip for what going on here

**Comment by mozuysal** [comment]
@cyrstem that is an unrelated issue while building the Python bindings, probably related to pybind11 version and GCC12 not playing nice with each other. In case you do not need to generate Python bindings you can turn it off when generating the build files

cmake . -B build -DNGP_BUILD_WITH_PYTHON_BINDINGS=OFF

That should skip the problematic step and you can generate/play with the executables.

In case you need the bindings then it might be better to open a separate issue and/or search pybind11 & gcc12 issues.

**Comment by ArthurChan2018** [comment]
I had the same problem while compiling.
Debian 12

$ g++ --version
g++ (Debian 12.2.0-14) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Nov__3_17:16:49_PDT_2023
Cuda compilation tools, release 12.3, V12.3.103
Build cuda_12.3.r12.3/compiler.33492891_0

**Comment by Tom94** [comment]
> Initialization of the two arrays of length 2 inside Testbed::Volume around L867 in testbed.h is likely the source of errors: // tracing state tcnn::GPUMemory pos[2] = {}; tcnn::GPUMemory payload[2] = {}; since these are arrays and the single initilizer list is possibly what trips the compiler. Changing these lines to // tracing state tcnn::GPUMemory pos[2] = {{}, {}}; tcnn::GPUMemory payload[2] = {{},{}}; solved the compilation errors and the code seems to work fine after the changes. However, I am not 100% sure this is the best solution.

Thank you. Without being sure *why* some compilers seem to require this, I pushed the change for now. This problem should be fixed.
