### ISSUE TITLE
small offset between rendered image from 3D model and corresponding pose from transform.json

### ISSUE THREAD

**Issue by arielbenitah** [NVlabs/instant-ngp#144]
Hi, once again, really amazing work!
I'm creating a 3D model using the `run.py` script you provided and try to align one of the camera pose I selected from `transform.json`  with the produced 3D model. I am doing this using `blender` by setting the `blender` camera to the selected pose. It seems to work whoever there is a small `translation` **offset** between both images.
I'm trying to understand **from where this offset is coming from**.

Below you can see the `blender` rendered image fused with a mask of a real image - corresponding to the selected pose in `transform.json`. As you can see there is a small offset between the two.
green is the mask of the real image.
purple is the rendered (from 3D model) `blender` image.

Thanks a lot for your help

![Screenshot from 2022-02-15 10-17-33](https://user-images.githubusercontent.com/10816903/154020771-ba2501ad-8724-4a24-b312-0cf128f80427.png)

**Comment by THELEMITED** [comment]
So the transformed. Image is a filter between the mutated laser that has been encrypted and deciphered for desoxy reverse proxy hopping...

I see you're looking for a poisoned dns picture form of a clout fourth cycle...

Le2-le3 on the list methods..

I have no idea what the polish police just said.

Watch out for the first I got a phishing shot of Iraq instead of knocking masons gf...

LMAO
Gl NGL

**Comment by mmalex** [comment]
hmm, I wonder if this is due to the camera distortion. can you try unchecking the 'apply camera distortion' (under > Nerf Rendering Opti0ons) and see if it reduces the error. if so, it may be that we have the principal point correction backwards. I don't remember it being wrong, but perhaps something has regressed... if that looks promising, take a look at the 'Screen Center' (under advanced camera settings). perhaps it needs to be 1.0-<whatever is there now>. That's my best guess where the offset is coming from... but I cant immediately explain why its wrong at the moment.

**Comment by Dmarcotrigiano** [comment]
Any update on whether this was this solution?

**Comment by jc211** [comment]
I'm getting the same thing

**Comment by Kikihqq** [comment]
> 

Can I ask you some questions? Thanks a lot.
when i train the model, i use `colmap2nerf.py` to generate the `transform.json`. I know the nerf style camera pose is `camera -> world`.
But how can i generate the querry json to render my camera pose? Do i need to change to `world to camera` pose?

**Comment by arielbenitah** [comment]
Hi, I'm closing this issue since I think that the offset I'm getting is not related with the ngp code.
