### ISSUE TITLE
how set train step when build or instant-ngp nerf/fox

### ISSUE THREAD

**Issue by 1346052851** [NVlabs/instant-ngp#1458]
how set train step when build or instant-ngp nerf/fox

**Comment by Tom94** [comment]
First, to be able to show the GUI, you need to compile without the `-DNGP_BUILD_WITH_GUI=OFF` configuration.

Then, to achieve your desired behavior, you can modify `src/main.cu` to call `testbed.init_window` only after a set number of training iterations have passed rather than at startup. If you want more involved scripting, I highly recommend using (and modifying) the Python environment `scripts/run.py` instead of the binary executable.
