### ISSUE TITLE
multi-resolution hashing in python / feature hashing ?

### ISSUE THREAD

**Issue by pwais** [NVlabs/instant-ngp#15]
In the paper, it was mentioned that the authors attempted to implement the multi-resolution hashing in python (e.g. Tensorflow) but it was 10x slower ... might that code be nevertheless made available for expository purposes?  It might make it easier to test this method on multiple GPUs / older GPUs despite the speed hit.

Also, the paper offers an initial explanation for why hash collisions don't hurt the results too much.  It might be possible to provide more rigorous analysis through the lens of feature hashing ( https://alex.smola.org/papers/2009/Weinbergeretal09.pdf ).

**Comment by Tom94** [comment]
Thanks you very much for the reference! This particular one wasn't on our radar, so we'll definitely have a closer look.

As for the Python implementation, it is unfortunately not in a well-tested enough state that I feel comfortable sharing it. It may have been sufficient as an exploratory tool -- to confirm that the encoding's benefits translate to NeRF prior to expending the effort of writing a bare-metal implementation (we had initially developed the encoding for radiance caching & SDFs) -- but for a code release I'd prefer re-implementing and thoroughly testing it from scratch. I agree that it would be great to have, but I can't yet say when we'll have the cycles to actually do it.

**Comment by pwais** [comment]
ok!  er, one more quick question on this topic.  The paper suggests you concatenate the NeRF-style "positional encoding" (equation 1-- `(sin 2^0 x, sin 2^1 x, ...) (cos 2^0 x, cos 2^1 x, ... ) with your multi-resolution hash encoding.  Table 2, if I read it right, suggests you tested ablating the hash encoding from the concatenated input:

<img width="1210" alt="Screen Shot 2022-01-16 at 1 54 54 PM" src="https://user-images.githubusercontent.com/218145/149679852-a2c5aef8-f391-41d4-b1bf-e4edd58bc1a3.png">

Just to be clear, the only thing being ablated here is the hash encoding?  (The paper alludes that the concatenation might include the hash encoding, the positional encoding, and perhaps other "textures in neural radiance caching"). Do I have this right at all?

Is there any easy way to reproduce this Table 2 / experiment in the code?  That would be really helpful for comparing methods.  It seems to me that the results from Table 2 _might_ reflect not just the hash encoding, but also, in part, the sampling strategy that the code implements.  And the speed-up appears akin to depth-supervised Nerf e.g. https://www.cs.cmu.edu/~dsnerf/  or some of the voxel-accelerated projects Vax-MipNerf https://github.com/naruya/Vax-MipNeRF  or DirectVoxGo https://github.com/sunset1995/DirectVoxGO (which you note in the paper and briefly show a related experiment in Fig 11) .   It strikes me that your "sampling improvements" give a 10x-100x speed-up, and the CUDA impl / Tensor core use give an additional 10x-100x, but that line is sort of blurry in Table 2.  (The Tensor core / fused MLP should probably be a ~10x boost by itself based upon what most nets gain through TensorRT).

**Comment by Tom94** [comment]
I think there's a misunderstanding:

- `Ours: Hash` refers to just the multiresolution hash encoding (config `nerf/base.json`).
- `Ours: Frequency` refers to just the NeRF-style positional encoding + an approximate NeRF-like network architecture (config `nerf/frequency.json`) implemented in our framework.

I wouldn't call this table an ablation. Rather, it's a demonstration of the training speed vs. established techniques trained to convergence. The `Ours: Frequency` rows serve the purpose of showing how much of our training speed-up originates from the fast CUDA implementation and __tiny-cuda-nn__ versus our new encoding.

We've included PSNR calculation in `run.py` for reproduction (although we use a different, internal script for actually generating the numbers in the table). The following command should give you the numbers of individual entries:
`./scripts/run.py --mode nerf --scene lego\transforms_train.json --test_transforms lego\transforms_test.json --nerf_compatibility --n_steps 40000`

(run.py does not currently allow specifying a training time rather than `n_steps`)

Add `--network frequency.json` to generate PSNRs from the `Ours: Frequency` rows. Otherwise, `base.json` is used by default and the PSNRs correspond to `Ours: Hash`.

**Comment by Tom94** [comment]
Regarding the second half of your comment: I completely agree that a certain proportion of our improvement over prior work likely originates from our sampling strategy, optimizer params, batch size (we use gigantic 256k-elems large batches, which train much quicker than smaller ones), and other implementation details.

This is precisely what the `Ours: Frequency` entries are meant to show in isolation without involving the hash encoding.

**Comment by pwais** [comment]
Thanks @Tom94 for the clarification and the reproduction instructions!  I didn't know the configs in the repo were there for that. 

I hear you that `nerf/frequency.json` and `Ours: Frequency` models the NeRF-style feature encoding.  For the the NVSF, MipNerf, and NeRF methods cited in Table 2, did you guys reproduce those as-is?  Because they likely use much much more costly ray sampling.  E.g. original NeRF: https://github.com/bmild/nerf/blob/18b8aebda6700ed659cb27a0c348b737a5f6ab60/run_nerf.py#L181   So I'm trying to say the PSNRs in Table 2 are kinda hard to compare because the other methods take a lot longer but also do a lot more ray sampling (have more info).  Table 2 is incredibly useful, I'm just saying the sampling issue might get lost on the reader.

**Comment by Tom94** [comment]
You're 100% right! The main reason we don't (yet) have more specific numbers w.r.t. mip-NeRF, NeRF, and NSVF (and mark their training time as ~hours rather than a concrete number) is that we took the numbers, referring to converged models, from the respective papers.

(+ crossreferenced the respective codebases to ensure PSNR is calculated in the same color spaces / alpha blend modes / compositing schemes which all have surprisingly large impact.)

If we end up reproducing them from scratch for the final version of the paper, we'll absolutely add extra details. Given the large training times required, we can not promise this will happen.

**Comment by pwais** [comment]
Yes trying to reproduce the others from scratch would take way too much time.  But perhaps something as simple as `number of rays * samples per ray * SGD iters` might be easy to report.  Here's an interesting comparison:

In Arandjelovic and Zisserman https://arxiv.org/pdf/2106.05264.pdf , they propose a "fancy" network to predict where to sample and can cut down sampling for vanilla NeRF by about 50% or so depending on the scene (Figure 3) in 150,000 SGD iters (page 6).  In contrast, your system requires 1000x fewer _SGD iters_.  I believe this is largely due to your ray sampling (which you actually talk about in the appendix section C.2, and in code here I believe: https://github.com/NVlabs/instant-ngp/blob/b8286072363e7c072c627c6d97757b9b0cdfb69a/src/testbed_nerf.cu#L906 ).  

I guess the thing for me is your paper specifically talks about "efficient implementation" around Table 2 and that made me think the gain was from `tcnn` or optimized CUDA code.  There is a gain from that, but I think there might be a bigger gain from "efficient ray sampling" ("Accelerated ray marching").  And it's notable that you get this gain w/out any learning (vs Arandjelovic and Zisserman).

**Comment by pwais** [comment]
FWIW, somebody has begun a python impl of the feature hashing technique: https://github.com/jenkspt/neural_hash_encoding

**Comment by Tom94** [comment]
>FWIW (if you get here via search engine etc) somebody has begun a python impl of the feature hashing technique: https://github.com/jenkspt/neural_hash_encoding

Thats really cool, thanks for linking! Once that implementation is more fleshed out, let's link to it from the readme.

>Yes trying to reproduce the others from scratch would take way too much time. But perhaps something as simple as number of rays * samples per ray * SGD iters might be easy to report. Here's an interesting comparison...

Just noticed I hadn't replied this yet. Absolutely, I think reporting the total number of samples that the respective models were trained from is a great idea for an updated version of the paper. It's gonna be fairly high up the priority ladder. :)
