### ISSUE TITLE
Room demo?

### ISSUE THREAD

**Issue by atx-barnes** [NVlabs/instant-ngp#16]
Could you possibly include the data folder for the large room demo you have shown next to the fox GIF and maybe how you were able to create it to look so good? i.e. scanning path, video or pictures, render, training settings, etc. I'd be very curious to do something similar in a medium to large space.

**Comment by mmalex** [comment]
it's not quite what you're after, as releasing datasets may take us a little longer and so - no promises. BUT! I did throw up a new nerf tips file today [tips](docs/nerf_dataset_tips.md) and it intentionally includes a screenshot of the camera path taken in the robot demo, for your edification :)
the training was a 1 minute iphone (I think) video, extracted to a hundred or so frames, with --aabb_scale 16, otherwise default parameters. hope that helps!

**Comment by atx-barnes** [comment]
Great thanks! Thanks for the info on the capture will try those settings.

**Comment by yohannes-taye** [comment]
> it's not quite what you're after, as releasing datasets may take us a little longer and so - no promises. BUT! I did throw up a new nerf tips file today in `docs/nerf_dataset_tips.md` and it intentionally includes a screenshot of the camera path taken in the robot demo, for your edification :) the training was a 1 minute iphone (I think) video, extracted to a hundred or so frames, with --aabb_scale 16 passed to the colmap2nerf.py script, otherwise default parameters. hope that helps!

Thank you!
