### ISSUE TITLE
how to mesh it and save obj without gui?

### ISSUE THREAD

**Issue by Evilom** [NVlabs/instant-ngp#218]
when i generated mesh in windows platform,the result mesh is very bad,and i saw a youtuber says linuxs can fix this problam, so i turn to wsl.
when i open fox with gui in wsl, it occurs Segmentation fault ,now i wants to generate mesh and save it in wsl without gui, how should i do?

**Comment by Tom94** [comment]
Hi there, a couple of comments:
- Switching the operating system will not affect the mesh export function. I believe you're talking about bycould's video, in which case the suboptimal mesh came from the fact that they used `colmap` to estimate the lego digger's camera poses, rather than using the bundled `lego/transforms_train.json`.
- You can export the mesh without GUI using the Python bindings. In particular, you can use `testbed.compute_marching_cubes_mesh(resolution=256)` to get the vertices as numpy arrays and `testbed.compute_and_save_marching_cubes_mesh(filename, resolution=256)` to directly save it.

Cheers!
