### ISSUE TITLE
m_nerf.training.cam_rot_offset is all NaN

### ISSUE THREAD

**Issue by songjin321** [NVlabs/instant-ngp#303]
https://github.com/NVlabs/instant-ngp/blob/36278eece434f3b4cfd68fe253bc995f27985ccb/include/neural-graphics-primitives/adam_optimizer.h#L108

the rotation offset variable is set to zero initial, so variable()/var_len will get NaN, use variable().normalized() will solve this problem

**Comment by Tom94** [comment]
Wow, good catch, thank you. There was an even bigger bug: the sign and magnitude of the rotation was incorrect -- so the direction component of the extrinsics optimization didn't work as advertised for a while. Fixed in https://github.com/NVlabs/instant-ngp/commit/af9434ec4d3861cfe22abe45b44e363f1c604103
