### ISSUE TITLE
code may be inconsistent with the paper

### ISSUE THREAD

**Issue by ViXbob** [NVlabs/instant-ngp#339]
I notice that in `testbed.cu::1645` the variable `m_per_level_scale` is set to `exp(ln(desired_resolution * (float)m_nerf.training.dataset.aabb_scale / (float)m_base_grid_resolution)/(m_num_levels-1))`. 

However, the formula in paper is `b = exp((ln(N_max) - ln(N_min))/(l-1))` coressponding to `m_per_level_scale=exp((ln(desired_resolution)-ln((float)m_base_grid_resolution))/(m_num_levels-1))`, I think. Do I misunderstand it?

**Comment by Tom94** [comment]
Hi there,

the division by `m_base_grid_resolution` inside of the logarithm is equivalent to subtracting `ln(m_base_grid_resolution)` outside of it.

The multiplication by `m_nerf.training.dataset.aabb_scale` _is_ omitted in the paper, though, and we should probably include it in the NeRF implementation details. Specifically: since NeRF scenes are scaled into the unit cube, larger pre-scaled scene extents (`m_nerf.training.dataset.aabb_scale > 1`) warrant a correspondingly finer `N_max`.

Cheers!

**Comment by ViXbob** [comment]
Okay. Thanks for your explanation!
