### ISSUE TITLE
Python Memory Leak

### ISSUE THREAD

**Issue by jc211** [NVlabs/instant-ngp#350]
In python, if I create a testbed and then delete it (garbage collect too), the gpu memory is not being freed. This was not the case before I think.

**Comment by Tom94** [comment]
Hi there, this is caused by the way __tiny-cuda-nn__ manages its temporary buffers: these aren't tied to any particular object but rather serve as dynamically-growing per-stream arenas.

To help in your use case, I just pushed a commit https://github.com/NVlabs/instant-ngp/commit/833f7303c3fadb81927c765cd67788209cf66f1c that adds the Python binding `ngp.free_temporary_memory()`. You can call this function after having deleted your testbed instance (or after a particularly taxing moment in your pipeline) to reset the memory arenas to zero size. If they're needed again later on, they'll dynamically grow again.

Aside note: pulling the latest commit might require a very particular submodule dance due to unrelated, but recent changes:
```sh
git pull origin master
git submodule sync --recursive
git submodule update --recursive
```

Cheers!
