### ISSUE TITLE
HI, I have some questions about the input coordinate x

### ISSUE THREAD

**Issue by JJJLLLTTT** [NVlabs/instant-ngp#38]
Congrats on this great work！
In the section of "3 MULTIRESOLUTION HASH ENCODING", the paper mentions that "The input coordinate x ∈ Rd is scaled by that level’s grid resolution". What is the coordinate reference system? And what is the numerical range of coordinates？Does the value range of coordinate affect the subsequent hash？
Thanks a lot in advance.

**Comment by Tom94** [comment]
Hi there! This is good feedback -- while the hashing works regardless of domain, the resolution parameters `N_min` and `N_max` from the paper only refer to true resolutions if `x` is in the unit cube. The lower resolutions being 1:1 also hinges on the unit cube assumption; otherwise, there's wrapping.

This is something we should definitely clarify in an updated version of the paper.

**Comment by JJJLLLTTT** [comment]
> Hi there! This is good feedback -- while spatial hashing works regardless of domain, the resolution parameters `N_min` and `N_max` from the paper only refer to true resolutions if `x` is in the unit cube. The lower resolutions being 1:1 also hinges on the unit cube assumption; otherwise, there's wrapping.
> 
> This is something we should definitely clarify in an updated version of the paper.

Thank you for your reply~
