### ISSUE TITLE
colmap2nerf.py NaN problem

### ISSUE THREAD

**Issue by ralonsoreyes** [NVlabs/instant-ngp#434]
colmap2nerf.py:280: RuntimeWarning: invalid value encountered in true_divide
  totp /= totw
[nan nan nan]
avg camera distance from origin nan
111 frames
writing transforms.json

[...]
"frames": [
    {
      "file_path": "./images/DJI_0353.JPG",
      "sharpness": 3097.7094803594714,
      "transform_matrix": [
        [
          -0.048770823394761034,
          -0.004720344356321631,
          0.9987988411756861,
          **NaN**
        ],

**Comment by AbrihaDavid** [comment]
I encountered the same problem while trying to make models from UAV imagery with the Zenmuse X7 camera.

**Comment by melhashash** [comment]
Were you able to solve this issue?

**Comment by AbrihaDavid** [comment]
Not yet

**Comment by killnice** [comment]
That means your camera poses  are not correct

**Comment by sipink** [comment]
Have the same exact issue when try to test a drone shot, tried a number of ways to solve but nothing does.

**Comment by Kaszanas** [comment]
I have changed two things that made the solver work:
- changed colmap matcher from exhaustive to sequential,
- Switched from input of pre-processed images to video input.

This worked in my case.

**Comment by aradhyamathur** [comment]
It seems that the problem arises from the `closest_point_2_lines(mf[:,3], mf[:,2], mg[:,3], mg[:,2])` in [line](https://github.com/NVlabs/instant-ngp/blob/528c7c5d18241817b99cfbe951127bdad23cfd6f/scripts/colmap2nerf.py#L308)  further if I look closely in the code the [`w>0.01`](https://github.com/NVlabs/instant-ngp/blob/528c7c5d18241817b99cfbe951127bdad23cfd6f/scripts/colmap2nerf.py#L309) is being hardcoded, for the images I was testing the value of `w` returned from `closest_point_2_lines` was much lower, perhaps manually setting it to lower value should do the trick to get it up and running, not really sure if that's the correct workaround but does prevent nans from coming. Further, [`f`](https://github.com/NVlabs/instant-ngp/blob/528c7c5d18241817b99cfbe951127bdad23cfd6f/scripts/colmap2nerf.py#L304) and [`g`](https://github.com/NVlabs/instant-ngp/blob/528c7c5d18241817b99cfbe951127bdad23cfd6f/scripts/colmap2nerf.py#L306) take values from the same set of frames, thus, for the same images in inner loop `w` will always be zero since the transformation matrices ([here](https://github.com/NVlabs/instant-ngp/blob/528c7c5d18241817b99cfbe951127bdad23cfd6f/scripts/colmap2nerf.py#L307) and  [here](https://github.com/NVlabs/instant-ngp/blob/528c7c5d18241817b99cfbe951127bdad23cfd6f/scripts/colmap2nerf.py#L305)) will be same so resulting in 0 vector and 0 [`denom`](https://github.com/NVlabs/instant-ngp/blob/528c7c5d18241817b99cfbe951127bdad23cfd6f/scripts/colmap2nerf.py#L148), so perhaps skip those frame indices.

**Comment by cjw531** [comment]
Thanks to @aradhyamathur , I changed the line `w > 0.01` in [`colmap2nerf.py`](https://github.com/NVlabs/instant-ngp/blob/528c7c5d18241817b99cfbe951127bdad23cfd6f/scripts/colmap2nerf.py#L309) into `w > 0.0001`.

Before lowering the threshold, the output:
```
RuntimeWarning: invalid value encountered in true_divide
  totp /= totw
[nan nan nan]
avg camera distance from origin nan
```

After lowering the threshold value into 0.0001, the output:
```
up vector was [-0.99801947 -0.06274485 -0.00449611]
computing center of attention...
[-317.74067482  -24.81560531   -0.35117663]
avg camera distance from origin 318.726712749806
```

It became non-nan values, and executes without warning.

**Comment by Tom94** [comment]
Thanks for pointing this out -- I've pushed a corresponding fix to `master`
