### ISSUE TITLE
Very quick question

### ISSUE THREAD

**Issue by greeneggsandyaml** [NVlabs/instant-ngp#53]
Hello, thank you for your great paper. I have a super quick question. Do you use (static, spherical, learned) background images for any of your results on 360-degree scenes? If not, how do you deal with the problem of very distant objects? I did not see this in the paper. 

Thank you very much for your work!

**Comment by mmalex** [comment]
hi! we do not use any background images (we did experiment with learned spherical envmap). in the end we just permit the rays to extend over quite a large range, and use a cascaded version of our acceleration structure to identify air/solid, which is lower resolution further from the origin. The step size along rays in the raymarcher is also exponential in this case, ie its a kind of cone tracer. we touch on this a little in appendix C at the very end of the paper.

we also investigated warping space far from the origin, but in the end we found that the best results were just with exponential stepping along the ray combined with the cascaded acceleration structure. for very big open air scenes, it does end up 'squashing' the scenery that is 'at infinity' onto the edges of the bounding box. 

I think it's plausible that we could get even better quality from stacked spherical images, but we haven't experimented with that, so that's purely hypothetical :)

**Comment by greeneggsandyaml** [comment]
Thanks so much for your quick and comprehensive response! I really appreciate it. 

The results on 360-degree scenes (from the videos/gifs displayed on your project page) are especially impressive considering that you didn't use any spherical environment maps. I read Appendix C and it's very nice, although I may have more 

Also, just to clarify, are all the components required for the big scenes (e.g. the multi scale occupancy grid) implemented in this repository? I didn't see them, but I thought that I should confirm.

**Comment by Tom94** [comment]
Yes, they’re all implemented. To get the 360 results, we use the same command line & config as the fox, just pointing it to a different dataset. :)

**Comment by mcourteaux** [comment]
Am I understanding correctly that you just use a very small `"scale"` factor in the config, to be able to fit the far objects in the bounding box?

**Comment by Tom94** [comment]
More or less -- we prefer using larger values of "aabb_scale" to enlarge the bounding box instead. The reason being that the multi-scale occupancy grid acceleration structure adapts to `aabb_scale` by introducing extra cascades, whereas "scale" really just scales down the scene without affecting anything about the algorithm.

If your goal is to fit even larger scenes, I recommend increasing `NERF_CASCADES()` within the C++ code to a value of 8 or so, which in turn allows a "aabb_scale" of up to 128 to be used (rather than the default value of 5, leading to a maximum "aabb_scale" of 16).

**Comment by mcourteaux** [comment]
Super interesting! I didn't know about this before. This feature definitely deserves a more visible location/documentation in the README or something. I was setting up comparisons of NeRF with my (unpublished) technique, and was scaling down the scenes to fit them into the box. This aabb_scale works a lot better for producing quality results it seems. :+1:
