### ISSUE TITLE
A quick question about the fox dataset

### ISSUE THREAD

**Issue by xTayEx** [NVlabs/instant-ngp#56]
Hello, thanks for your great paper. I would like to know how you generate the fox dataset. I take some photos of real world objects, and use the colmap2nerf.py script to process them. However. I didn't get a good training result using the new dataset. One of the original photos and the training result are shown bellow.

**Comment by xTayEx** [comment]
![0001](https://user-images.githubusercontent.com/40186387/150093299-1bb38be6-1e7b-4e3d-b48a-a991bfe76754.jpg)

![image](https://user-images.githubusercontent.com/40186387/150093401-3902c428-2a26-46c9-8e91-487a091848fa.png)

**Comment by mmalex** [comment]
hi! the fox was just a few seconds iphone video, with a few frames selected to minimise blur and to cover a range of angles. you can see the chosen frames in the data/nerf/fox/images folder. the colmap2nerf script was used with default parameters apart from --aabb_scale 4 which basically says 'theres a small amount of background visible in the distance, outside the main bounding box'. see the nerf tips document for more info. the reconstruction you are showing above is indeed quite bad! how many images do you have? are they from a range of angles? have you checked if COLMAP was able to create accurate camera poses? (you can do that by using the COLMAP gui and running colmap manually). without seeing the dataset itself it's hard to know what's going wrong. 

clutching at straws, perhaps the lack of contrast between the foreground and background is leading to the problem. The NeRF algorithm basically works by adjusting the density (shape) so that random training rays 'agree' on the color of the pixel. I can imagine that if the foreground and background objects are very similar in color, only the shadows will help to drive the algorithm towards convergence. so perhaps that could be it... but as I say, Id have to look at the data more to understand it. I would expect a scene of that complexity to be fittable fairly easily.

**Comment by xTayEx** [comment]
Thank you so much for your reply! I have made some progress in creating dataset. Instead of using the fan object shown above, now I am using a rubber duck to create my new dataset. Instant-ngp can reconstruct my duck, but there is so muck 'dust' around it as shown below. 
![image](https://user-images.githubusercontent.com/40186387/150271153-ec0b33d1-8d63-405c-b6a6-5bf9e29ca68b.png)

I have checked my rubber duck dataset with COLMAP, the camera poses seems right. However, I found that the duck cant be reconstruct well in COLMAP. Would it be the cause of the 'dust'?

Below is the COLMAP analysis result and one of the rubber duck photos.

![image](https://user-images.githubusercontent.com/40186387/150271769-c478ccd7-c61d-42d1-9fa3-a9b42c7613b1.png)

![0052](https://user-images.githubusercontent.com/40186387/150271863-edde95b2-2cdd-46d4-a663-8a7a79193c69.jpg)

**Comment by xTayEx** [comment]
To generate the dataset, I used colmap2nerf with default parameters apart from --aabb_scale 4.

**Comment by mhalber** [comment]
One tip that I have from my experiments - visualize cameras and ensure that the near distance is set appropriately. If I understand correctly, if your near clipping distance is too far from the actual focal plane, then the algorithm will never sample there, and hence it will never be able to clear out the "dust"

**Comment by xTayEx** [comment]
I use colmap2nerd.py in commit [bb00a1](https://github.com/NVlabs/instant-ngp/commit/bb00a1e41b882a98ad25298cfc3ae0456b0fd544) to regenerate my dataset, then it works magically! Someone who has the same problem can try it.

**Comment by MiZhenxing** [comment]
> I use colmap2nerd.py in commit [bb00a1](https://github.com/NVlabs/instant-ngp/commit/bb00a1e41b882a98ad25298cfc3ae0456b0fd544) to regenerate my dataset, then it works magically! Someone who has the same problem can try it.

Great!

**Comment by ZepSbosnia** [comment]
Hi, I've faced the same problem. I think that the 'dust' is caused by the the picture blur. Indeed I've preprocessed the images removing the background and the results really improved: 
![pidgeot_colmap_instant_nobk](https://user-images.githubusercontent.com/113693846/190639390-2911c9cd-5b60-4c10-a941-7261a3fa2498.png)
![pidgeot_colmap_instant](https://user-images.githubusercontent.com/113693846/190639393-b6ce49ec-c4f4-44f7-8386-d58a44cf5132.png)

The question now is how to use the code fore more complicate scenes

**Comment by ZepSbosnia** [comment]
Hi, I've faced the same problem. I think that the 'dust' is caused by the the picture blur. Indeed I've preprocessed the images removing the background and the results really improved:
![pidgeot_colmap_instant](https://user-images.githubusercontent.com/113693846/190639691-836241d2-3c62-4379-a2b1-892b1404ae90.png)
![pidgeot_colmap_instant_nobk](https://user-images.githubusercontent.com/113693846/190639725-7c643066-28d3-462d-8f22-22d4f458713c.png)
the input was like : 
![000](https://user-images.githubusercontent.com/113693846/190639882-bfd3ccb0-7d1d-4951-84e4-4bf6ba752975.jpg)
an running  rembg p path/to/the/images path/to/images/processed becomes :
![download](https://user-images.githubusercontent.com/113693846/190640146-21548afc-6a5b-464d-ba9e-20cc7dda208d.png)

the question is how to use the code for more complicated scenes...

**Comment by zhangsirya** [comment]
> Hi, I've faced the same problem. I think that the 'dust' is caused by the the picture blur. Indeed I've preprocessed the images removing the background and the results really improved: before ![pidgeot_colmap_instant](https://user-images.githubusercontent.com/113693846/190639691-836241d2-3c62-4379-a2b1-892b1404ae90.png) after ![pidgeot_colmap_instant_nobk](https://user-images.githubusercontent.com/113693846/190639725-7c643066-28d3-462d-8f22-22d4f458713c.png) the input was like : ![000](https://user-images.githubusercontent.com/113693846/190639882-bfd3ccb0-7d1d-4951-84e4-4bf6ba752975.jpg) an running rembg p path/to/the/images path/to/images/processed becomes : ![download](https://user-images.githubusercontent.com/113693846/190640146-21548afc-6a5b-464d-ba9e-20cc7dda208d.png)
> 
> the question is how to use the code for more complicated scenes...



> Hi, I've faced the same problem. I think that the 'dust' is caused by the the picture blur. Indeed I've preprocessed the images removing the background and the results really improved: before ![pidgeot_colmap_instant](https://user-images.githubusercontent.com/113693846/190639691-836241d2-3c62-4379-a2b1-892b1404ae90.png) after ![pidgeot_colmap_instant_nobk](https://user-images.githubusercontent.com/113693846/190639725-7c643066-28d3-462d-8f22-22d4f458713c.png) the input was like : ![000](https://user-images.githubusercontent.com/113693846/190639882-bfd3ccb0-7d1d-4951-84e4-4bf6ba752975.jpg) an running rembg p path/to/the/images path/to/images/processed becomes : ![download](https://user-images.githubusercontent.com/113693846/190640146-21548afc-6a5b-464d-ba9e-20cc7dda208d.png)
> 
> the question is how to use the code for more complicated scenes...

Hello, may I ask how you remove the background? After removing the background, won't the black background be recreated?

**Comment by zhangsirya** [comment]
> Hi, I've faced the same problem. I think that the 'dust' is caused by the the picture blur. Indeed I've preprocessed the images removing the background and the results really improved: before ![pidgeot_colmap_instant](https://user-images.githubusercontent.com/113693846/190639691-836241d2-3c62-4379-a2b1-892b1404ae90.png) after ![pidgeot_colmap_instant_nobk](https://user-images.githubusercontent.com/113693846/190639725-7c643066-28d3-462d-8f22-22d4f458713c.png) the input was like : ![000](https://user-images.githubusercontent.com/113693846/190639882-bfd3ccb0-7d1d-4951-84e4-4bf6ba752975.jpg) an running rembg p path/to/the/images path/to/images/processed becomes : ![download](https://user-images.githubusercontent.com/113693846/190640146-21548afc-6a5b-464d-ba9e-20cc7dda208d.png)
> 
> the question is how to use the code for more complicated scen
Hello, may I ask how you remove the background? After removing the background, won't the black background be recreated?

**Comment by zhangsirya** [comment]
> Hi, I've faced the same problem. I think that the 'dust' is caused by the the picture blur. Indeed I've preprocessed the images removing the background and the results really improved:

Hello, may I ask how you remove the background? After removing the background, won't the black background be recreated?

**Comment by ZepSbosnia** [comment]
Hi, it depends how you remove the background. In my case i have set it transparent using RGBA color space (alpha channel is the transparent one) then saving in png format instant nerf won't consider the transparent colors. 
while to get better resolution of the obj i suggest to decrease the aabb value

**Comment by zhangsirya** [comment]
Wow, thank you for your response! I will try it out right away.
