### ISSUE TITLE
COLMAP Feature Extraction -  FATAL: command failed

### ISSUE THREAD

**Issue by hanikhatib** [NVlabs/instant-ngp#672]
So I used the command to run colmap on my custom images. After about 33 minutes of training, I receive an unexpected error and the transforms.json file is still not made. I am running this on Colab, I have GPUs enabled but I am not necessarily using GPUs on my runtime. Below is the error after all the images were iterated through:
...
 ```
 Processed file [123/123]
  Name:            IMG_7532.jpg
  Dimensions:      4032 x 3024
  Camera:          1 (OPENCV)
  Focal Length:    2995.20px (EXIF)
  GPS:             LAT=43.650, LON=79.383, ALT=125.576 (EXIF)
  Features:        10052
Elapsed time: 33.672 [minutes]

==== running: colmap exhaustive_matcher --SiftMatching.guided_matching=true --database_path colmap.db
*** Aborted at 1654791679 (unix time) try "date -d @1654791679" if you are using GNU date ***
PC: @     0x7f84c3ccbbf8 (unknown)
*** SIGSEGV (@0xe0) received by PID 4530 (TID 0x7f84d6834900) from PID 224; stack trace: ***
    @     0x7f84d53e4980 (unknown)
    @     0x7f84c3ccbbf8 (unknown)
    @     0x7f84c3ccbff8 (unknown)
    @     0x7f84d42cb11f QOpenGLContext::create()
    @     0x555f3d3118ae (unknown)
    @     0x555f3d28a8a1 (unknown)
    @     0x555f3d28cec7 (unknown)
    @     0x555f3d28dae0 (unknown)
    @     0x555f3d190343 (unknown)
    @     0x555f3d180ba7 (unknown)
    @     0x7f84d2b04c87 __libc_start_main
    @     0x555f3d18444a (unknown)
Segmentation fault (core dumped)
FATAL: command failed
```

**Comment by jere357** [comment]
Features:        603
Elapsed time: 0.017 [minutes]
==== running: colmap sequential_matcher --SiftMatching.guided_matching=true --database_path colmap.db

==============================================================================
Sequential feature matching
==============================================================================

Matching image [1/19]ERROR: Feature matching failed. This is probably caused by insufficient GPU memory. Consider reducing the maximum number of features and/or matches.
ERROR: Feature matching failed. This is probably caused by insufficient GPU memory. Consider reducing the maximum number of features and/or matches.
ERROR: Feature matching failed. This is probably caused by insufficient GPU memory. Consider reducing the maximum number of features and/or matches.
ERROR: Feature matching failed. This is probably caused by insufficient GPU memory. Consider reducing the maximum number of features and/or matches.
ERROR: Feature matching failed. This is probably caused by insufficient GPU memory. Consider reducing the maximum number of features and/or matches.
 I am also getting an error while running it on a 3090 - it worked ok a couple of days ago i have no idea what changed

**Comment by hanikhatib** [comment]
Regarding your issue, it really looks like a memory bottleneck. Regarding the initial issue I posted, I do not believe there is a consistent workaround for GUIs on Colab.

**Comment by KcLimitless** [comment]
This is not an error, it means you are running out of memory. simply create more space in your hard drive by deleting some things you don't need and empty your trash too. Then everything will work fine.

**Comment by KcLimitless** [comment]
> So I used the command to run colmap on my custom images. After about 33 minutes of training, I receive an unexpected error and the transforms.json file is still not made. I am running this on Colab, I have GPUs enabled but I am not necessarily using GPUs on my runtime. Below is the error after all the images were iterated through: ...
> 
> ```
> Processed file [123/123]
>  Name:            IMG_7532.jpg
>  Dimensions:      4032 x 3024
>  Camera:          1 (OPENCV)
>  Focal Length:    2995.20px (EXIF)
>  GPS:             LAT=43.650, LON=79.383, ALT=125.576 (EXIF)
>  Features:        10052
> Elapsed time: 33.672 [minutes]
> 
> ==== running: colmap exhaustive_matcher --SiftMatching.guided_matching=true --database_path colmap.db
> *** Aborted at 1654791679 (unix time) try "date -d @1654791679" if you are using GNU date ***
> PC: @     0x7f84c3ccbbf8 (unknown)
> *** SIGSEGV (@0xe0) received by PID 4530 (TID 0x7f84d6834900) from PID 224; stack trace: ***
>    @     0x7f84d53e4980 (unknown)
>    @     0x7f84c3ccbbf8 (unknown)
>    @     0x7f84c3ccbff8 (unknown)
>    @     0x7f84d42cb11f QOpenGLContext::create()
>    @     0x555f3d3118ae (unknown)
>    @     0x555f3d28a8a1 (unknown)
>    @     0x555f3d28cec7 (unknown)
>    @     0x555f3d28dae0 (unknown)
>    @     0x555f3d190343 (unknown)
>    @     0x555f3d180ba7 (unknown)
>    @     0x7f84d2b04c87 __libc_start_main
>    @     0x555f3d18444a (unknown)
> Segmentation fault (core dumped)
> FATAL: command failed
> ```

**Comment by KcLimitless** [comment]
This is not an error, it means you are running out of memory. simply create more space in your hard drive by deleting some things you don't need and empty your trash too. Then everything will work fine.

**Comment by KcLimitless** [comment]
This is not an error, it means you are running out of memory. simply create more space in your hard drive by deleting some things you don't need and empty your trash too. Then everything will work fine.
