### ISSUE TITLE
Benchmarking nerf

### ISSUE THREAD

**Issue by kwea123** [NVlabs/instant-ngp#744]
Hi, I tried to reproduce paper result, but cannot get to the number reported. The following is how I did the experiment, could you tell me where I did wrong?

https://github.com/kwea123/ngp_pl/issues/3#issuecomment-1175773671

**Comment by Tom94** [comment]
Hi there, the NeRF / NSVF / mip-NeRF codebases do not respect color spaces / pre-multiplied alpha correctly and hence their PSNR calculation behaves in non-intuitive ways. __instant-ngp__ tries to be more principled about it, resulting on worse PSNR numbers by default, but you can revert to original NeRF's behavior with the `--nerf_compatibility` argument.

The following command should let you reproduce the numbers from the paper:
```sh
./run.py --mode nerf --nerf_compatibility --scene lego/transforms_train.json --test_transforms lego/transforms_test.json 
```

PS: note that you can just pass `lego/transforms_train.json` instead of the folder to avoid having to delete validation and test transforms.
