### ISSUE TITLE
How to deal with alpha channel? 

### ISSUE THREAD

**Issue by liu-vis** [NVlabs/instant-ngp#92]
Hi, thank you for the great work!!
I tested instant-ngp-nerf on the "nerf_synthetic/lego" dataset. It works very well. However, I found that if I convert a lego image from RGBA (it has RGB channels and an alpha channel) to RGB by either the two ways written below, instant-ngp-nerf cannot perform well. Could you please let me know if my experiment was done correctly?
The methods I used to convert ARGB to RGB are:
 1) https://stackoverflow.com/questions/2049230/convert-rgba-color-to-rgb
2) rgb_image = rgba_image[:, :, :-1]  (It means that the alpha channel is simply removed)

The results of "nerf_synthetic/lego/test" are shown below: 
[from left to right] Trained on RGBA images  |  Trained on RGB images obtained by 1)  |  Trained on RGB images obtained by 2)  |   GT
![lego_compare_argb_rgb_AdobeCreativeCloudExpress](https://user-images.githubusercontent.com/28891082/151667986-fb215a26-8222-4ed0-97f8-2b730513815b.gif)

I will appreciate it if you could also share some tips for running instant-ngp-nerf on RGB images recorded by some device such as an IPhone.

**Comment by Tom94** [comment]
Hi there,

__instant-ngp__ should work fine with RGB colors since there's no supervision using Alpha. That said, when there's an alpha channel, the background color is _randomly_ chosen for each training sample.

You can disable this and obtain pure RGB training directly from the GUI or Python by setting the background color. E.g. to get training on white-composited images:
```python
testbed.background_color = [1.0, 1.0, 1.0, 1.0]
testbed.nerf.training.random_bg_color = False
```

As for your actual problem: it is quite strange and unexpected to me. I suspect the following is happening, but please follow up if I'm wrong.
- If you're launching __instant-ngp__ via `--scene lego`, then it will load and train from _all_ images it can find, including the `test` and `val` subfolders.
- Could it be that you're converting just the images in the `lego/train` folder, but using the above argument to load training data? That might lead to such a problem, because training data will be mixed RGB/RGBA.
- The fix in this case would be to use `--scene lego/transforms_train.json` to load just the training images. This should have identical behavior to the two lines of python code above.

**Comment by liu-vis** [comment]
Thank you very much for your answer!
I trained instant-ngp-nerf via 
```
python ./scripts/run.py --training_data $LEGO_DATA/transforms_train.json --save_snapshot $PATH_TO_SAVE --n_steps 20000
```
and tested the model via 
```
python ./scripts/run.py --load_snapshot $PATH_TO_SAVE --test_transforms $LEGO_DATA/transforms_test.json --screenshot_dir $SOMEWHERE
```

Let me try the following settings and check if it solves my problem. Thank you for the suggestion.
```
testbed.background_color = [1.0, 1.0, 1.0, 1.0]
testbed.nerf.training.random_bg_color = False
```
As for the problem that if an alpha channel has an impact on training, I actually did some experiments. 
I first took the alpha channel of a training image, converted it into a 0/255 mask (via alpha[alpha > 0] = 255). Then, I altered the size of its white region (the region with its values equivalent to 255). After that, I concatenate the altered alpha channel (H x W) back to the RGB channels (H x W x 3) via `im.putalpha(altered_alpha)` where `im` and `altered_alpha` are `PIL.Image`. The results are shown below:
![lego_compare_alphaMat_size_AdobeCreativeCloudExpress](https://user-images.githubusercontent.com/28891082/151697650-0539fd8b-9e05-4aba-8e69-a2bc31ab59ef.gif)
The first row are four examples that show how much the alpha channel of a training image is altered (dilated). 
The second row is the results of the test samples.
It seems that the training process is somehow affected by the alpha channels. 
I am not sure if the results are helpful, just put them here in case they are.

**Comment by Tom94** [comment]
Thanks for the extra info, this is really helpful!

I dug a bit deeper and managed to reproduce your issue after having converted the dataset with
```python
for file in os.listdir(args.scene):
	img = common.read_image(os.path.join(args.scene, file))
	img += (1.0 - img[...,3:4]) * np.array([0.0, 0.0, 0.0, 1.0])
	common.rite_image(os.path.join(args.scene, file), img)
```

I was confused at first, but thinking the problem more, I think it makes sense. See below.

The fix is as follows: you need to set
```python
testbed.background_color = [R, G, B, 1.0]
testbed.nerf.training.random_bg_color = False
```
as mentioned above, but where `R`, `G`, and `B` are the actual background color that you use. `0` for black and `1` for white. (This is similar to the original NeRF code where background color is also assumes as known.)

If you don't do this (and if `random_bg_color == True`), the model is forced to be opaque everywhere, because any rays that don't collide with anything would have the wrong background color.

This is no problem for real RGB scenes recorded with an iPhone, because the real world requires fitting a model everywhere anyway.
But for these synthetic scenes where transparency is expected, the background must either be marked with an alpha channel or it must be known color.

**Comment by liu-vis** [comment]
Great!! Thank you so much for the answer and explanation!
My problem is solved. 
I tested multiple cases based on your suggestions, the model worked fine for all of them.
