### ISSUE TITLE
Error when loading nerf datasets

### ISSUE THREAD

**Issue by Jorgelzn** [NVlabs/instant-ngp#95]
The program gives me the following error and i don´t know how to solve it.

ERROR    Uncaught exception: Could not allocate memory: CUDA Error: cudaMalloc(&rawptr, n_bytes+DEBUG_GUARD_SIZE*2) failed with error out of memory
![Captura de pantalla 2022-01-29 184514](https://user-images.githubusercontent.com/53486164/151671603-69bb18b3-8c55-4da2-b7cf-0691e360ec35.png)

**Comment by lone101** [comment]
Same error here

**Comment by PL-AD** [comment]
Well, I don't know nothing about coding and everything, but I like to test stupid things, and I had the same problem, because my 3070 is really short on memory for custom scenes, and the Fox one too. But it was working with the lego one, so I tried to replicate the json file from the lego scene into my own json file : for exemple deleting the first lines to only keep "camera angle_x" and then the different frames. I also had to start the command with a way tu reduce the window, something like :
" ./build/testbed --scene data/nerf_synthetic/[name_of_project]/transforms.json --width 1280 --height 720 "
In the end it worked, but the 8Go VRAM is short because if I try to resize the window while working, it shuts down the NeRF render window

**Comment by Tom94** [comment]
Hi there, see https://github.com/NVlabs/instant-ngp/issues/36 for more information and VRAM constraints. Unfortunately, 8 gigs are pushing the envelope for NeRF
